spring:
  application:
    name: interpark-clone

  config:
    import: optional:file:.env[.properties]

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  jpa:
    open-in-view: false

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

cookie:
  secure: true
  same-site: Lax

redisson:
  connection-minimum-idle-size: 24
  connection-pool-size: 64

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
